### ISSUE TITLE
Hamburger icon on xSolidFigure.me for desktops

### ISSUE THREAD

**Issue by xSolidFigure** [xSolidFigure/xSFSite#2]
After I've updated CSS files and added GitCities button, I'm aware that some of you noticed a bug. 
![image](https://user-images.githubusercontent.com/22672279/38455615-dc617a74-3aa4-11e8-8548-284f660b50cd.png)

Even worse, if you're visiting it on mobile, you'll see this:
![image](https://cdn.discordapp.com/attachments/402778930920030211/432174901554577408/Screenshot_2018-04-07-20-48-21.png)

We're working on it to fix the issue.

**Comment by TTtie** [comment]
Can reproduce, the navbar appears also on the left side too. 
![obrazek](https://user-images.githubusercontent.com/17570452/38455730-94169a1a-3a7c-11e8-90bd-945510287061.png)

**Comment by xSolidFigure** [comment]
**UPDATE**: Looks like the hamburger icon isn't shown on desktops anymore, but unfortunately the hamburger icon is misplaced on mobile and side navigation isn't showing.

![image](https://cdn.discordapp.com/attachments/418185242256474112/432579190366142464/Screenshot_20180408-233456.png)

**Comment by xSolidFigure** [comment]
**UPDATE**: Problem has been resolved. The issue is now closed.

![image](https://cdn.discordapp.com/attachments/418185242256474112/432581725122592769/Screenshot_20180408-234458.png)
